### ISSUE TITLE
태스크 생성시, 시간 세팅에서 시간 String 포맷 체크를 어떻게 해야 하는가

### ISSUE THREAD

**Issue by conquerex** [Nexters/gamsung-routine-backend#9]
현재 RoutineTaskDto에서 times는 String으로 되어 있다.

이를 매주마다 unit 생성을 위해 태스크 생성시 미리 시간 포맷이 맞는지 확인이 필요하다.

어떻게 valid 할수 있을까?

----

**RoutineTaskDto 링크**
- https://github.com/Nexters/gamsung-routine-backend/blob/master/src/main/kotlin/com/gamsung/api/dto/RoutineTaskDto.kt

**Comment by conquerex** [comment]
**[추가]**

- 헌진 : 카테고리도 nullable한건지 확인도좀 부탁!

**Comment by teddykwon** [comment]
@DateTimeFormatter 라고 있는데, 그거를 쓰면 ISO_8601 형태로 주고 받을 수 있어서 좋아요!

**Comment by conquerex** [comment]
@teddykwon SimpleDateFormat으로 일단 만들어봤습니다.
